[general]
context=outbound
disallow=all
allow=ulaw
allow=alaw
udpbindaddr=0.0.0.0:5060
nat=force_rport,comedia
directmedia=no
externaddr=192.168.2.10          ; <-- IP du Mac
localnet=172.16.0.0/12           ; reseaux Docker = locaux

[pstn-out] ; used for dialing out
type=peer ; peers help deliver the calls for us.
host=192.168.2.2 ; (This is the IP of the MP-114)
context=outbound ; not necessary to, but lets us know its function
disallow=all
allow=ulaw
allow=alaw
dtmfmode=inband
nat=force_rport,comedia
qualify=yes
