[general]
context=outbond
disallow=all
allow=ulaw
allow=alaw
allow=gsm

[pstn-out] ; used for dialing out
type=peer ; peers help deliver the calls for us.
host=192.168.2.2 ; (This is the IP of the MP-114)
context=outbound ; not necessary to, but lets us know its function
disallow=all
allow=ulaw
allow=alaw
allow=gsm
dtmfmode=inband
nat=no
qualify=yes
